export enum ActivityType {
    LOGIN = 'LOGIN',
    LOGOUT = 'LOGOUT',
    BOOKING_CREATED = 'BOOKING_CREATED',
    BOOKING_CANCELLED = 'BOOKING_CANCELLED',
    PAYMENT = 'PAYMENT',
    REVIEW_POSTED = 'REVIEW_POSTED',
    VENUE_UPDATED = 'VENUE_UPDATED',
    USER_UPDATED = 'USER_UPDATED',
    VENUE_APPROVED = 'VENUE_APPROVED',
    VENUE_REJECTED = 'VENUE_REJECTED',

    // AI and User Behavior tracking
    VIEW_VENUE = 'VIEW_VENUE',
    VIEW_COURT = 'VIEW_COURT',
    SEARCH_QUERY = 'SEARCH_QUERY',
    FAVORITE_TOGGLE = 'FAVORITE_TOGGLE',
    PROMOTION_CLICK = 'PROMOTION_CLICK',
    AI_CHAT_START = 'AI_CHAT_START'
}
