export enum FileCategory {
    AVATAR = 'AVATAR',
    VENUE_IMAGE = 'VENUE_IMAGE',
    COURT_IMAGE = 'COURT_IMAGE',
    REVIEW_IMAGE = 'REVIEW_IMAGE',
    DOCUMENT = 'DOCUMENT',
    CONTENT_IMAGE = 'CONTENT_IMAGE',
    BANNER_IMAGE = 'BANNER_IMAGE',
    BLOG_IMAGE = 'BLOG_IMAGE'
}
