export enum SportType {
    FOOTBALL = 'FOOTBALL',
    FOOTBALL_5 = 'FOOTBALL_5',
    FOOTBALL_7 = 'FOOTBALL_7',
    FOOTBALL_11 = 'FOOTBALL_11',
    BASKETBALL = 'BASKETBALL',
    TENNIS = 'TENNIS',
    PICKLEBALL = 'PICKLEBALL',
    BADMINTON = 'BADMINTON',
    VOLLEYBALL = 'VOLLEYBALL',
    TABLE_TENNIS = 'TABLE_TENNIS',
}
