export enum SportType {
    FOOTBALL = 'FOOTBALL',
    BASKETBALL = 'BASKETBALL',
    TENNIS = 'TENNIS',
    BADMINTON = 'BADMINTON',
    VOLLEYBALL = 'VOLLEYBALL',
    TABLE_TENNIS = 'TABLE_TENNIS',
}
